### ISSUE TITLE
Getting PHP Fatal error:  Uncaught InvalidArgumentException: Signature mismatch: 

### ISSUE THREAD

**Issue by PPanon** [iqb/ecryptfs#1]
This is likely more a user issue than a bug.

My ecryptfs'd home dir got corrupted and somehow lost the file list for the home directory itself. It's possible to access files and directories if I know the name but not otherwise (so the encryption is a little too good :-)). I was able to copy out all the files and directories that I could remember, but there are still a lot that I need to get out. I thought I would try to use your userspace tool to decrypt all the directory+file names at the top level of the .Private directory and then copy out that list. 
I've moved the Private.mnt mount point so it's one directory down inside the new home directory structure for what I've managed to recover/move out of ecryptfs, and so that it doesn't conflict with my unencrypted/current home directory environment.

I appear to have installed the ecryptfs tarball correctly because I can successfully run the sample code in the Readme.MD

I then pulled out the passphrase with ecryptfs-unwrap-passphrase, took the results and changed the passphrase line in the example to
$passphrase = hex2bin('thehexstringfromunwrappassphrase');

However when I run it with php -f and it gets down to 
if (\Iqb\Ecryptfs\Util::decryptFilename($cryptoEngine, 'ECRYPTFS_FNEK_ENCRYPTED.....
and I substitute a filename from the .Private directory, I get 

PHP Fatal error:  Uncaught InvalidArgumentException: Signature mismatch: require a68f978bb61310c7, got 5f60a69ee0548e70 in /home/ppanon/PAOverflow/decrypthomedir/ecryptfs-master/src/Tag70Packet.php:151
Stack trace:
#0 /home/...mypath.../ecryptfs-master/src/Util.php(211): Iqb\Ecryptfs\Tag70Packet->decrypt(Object(Iqb\Ecryptfs\OpenSslCryptoEngine), '\x03\...')
#1 /home/...mypath.../ecryptfs-master/decryptfiles.php(14): Iqb\Ecryptfs\Util::decryptFilename(Object(Iqb\Ecryptfs\OpenSslCryptoEngine), 'ECRYPTFS_FNEK_E...', '\x03\...')
#2 {main}
  thrown in /home/...mypath.../ecryptfs-master/src/Tag70Packet.php on line 151

(where ...mypath... is a few [unencrypted] directory levels under my home directory, and I also did some other edits on the fnek value to avoid giving away too much)

I assume that the Signature mismatch indicates I need to change a signature somewhere to use the signature from Private.sig (even though the signature entries there don't match either of the above entries in that error message). However I'm at a loss of how to do that and would appreciate a pointer.

**Comment by DennisBirkholz** [comment]
Hello,

thanks for trying to use my package.

A signature is a hash of a key. The error you encounter indicates that you use the wrong key to decrypt the filenames.

You can generate the key for filename encryption using the `Util::deriveFNEK` method and the key for the data encryption key encryption `Util::deriveFEKEK`. You can print out the signature for each of the keys by using the using the `Util::calculateSignature` method:

```
echo "FNEK: ", Util::calculateSignature(Util::deriveFNEK($passphase)), PHP_EOL;
echo "FEKEK: ", Util::calculateSignature(Util::deriveFEKEK($passphase)), PHP_EOL;
```

The signature of the FNEK should be a68f978bb61310c7, otherwise the extracted passphrase is wrong. Maybe you do not need to hex decode the extracted passphrase, calculate the signatures without using hex2bin. Hopefully this will get you access to the filenames.

Greets
Dennis

**Comment by PPanon** [comment]
Well, if I don't use hex2bin, then the FNEK sig is 2ac13a17db223ae3, which doesn't match either.
However the passphrase I get from ecryptfs-unwrap-passphrase should be correct. If I make a typo on the password that I submit for that command then I get:
Error: Unwrapping passphrase failed [-5]
Info: Check the system log for more information from libecryptfs
with
ecryptfs-unwrap-passphrase: Incorrect wrapping key for file [/home/ppanon/.ecryptfs/wrapped-passphrase]
in syslog, so the ecryptfs devs presumably have a magic cookie in the wrapped passphrase which has to be checked as part of the unwrapping. The resulting passphrase is in [a-f0-9]+, which is why I had guessed that it might need converting to string. For a while I was thinking that perhaps hex2bin wasn't converting properly if the line contained a CR or LF, because the resulting string looked too short. But that must have just been skipping unprintable characters since the strlen() of the hex2bin()ed  passphrase appears to be the correct value - 1/2 the (presumably) hex-encoded encoded string.

Could deriveFNEK be choking on non alphanumeric characters?

**Comment by DennisBirkholz** [comment]
> Could deriveFNEK be choking on non alphanumeric characters?

That should not be a problem, all methods involved are binary save.

Lets try to debug the key material. For the following examples I used the passphrase "testtest" so showing the keys here is no security breach or anything.

You can use the `ecryptfs-insert-wrapped-passphrase-into-keyring` command to derive both the FNEK and the FEKEK from the wrapped passphrase and insert it into the kernel keyring. The command will ask for your password to unwrap the passphrase and displays something like this:

```
$ ecryptfs-insert-wrapped-passphrase-into-keyring $wrapped-passphrase-file
> Inserted auth tok with sig [d1a01d50c3f21e00] into the user session keyring
```

The signature is the signature of the FEKEK.
Use the `keyctl` command to list the keys inserted into the kernel keyring. You can install the `keyctl` command with `apt-get install keyutils`.
```
$ keyctl list '@u'
> Keyring
>   420076798 --alswrv      0 65534  keyring: _uid.0
>   808317687 --alswrv      0     0   \_ user: 2ba618ba097162ff    << FNEK
>   651176014 --alswrv      0     0   \_ user: d1a01d50c3f21e00    << FEKEK
```

You see two keys there, the FEKEK with the signature from above (d1a01d50c3f21e00) and a second key which is the FNEK (signature 2ba618ba097162ff).

You can now print the FNEK. You have to use the ID that is the leftmost column from the listing above.
```
$ keyctl print 808317687
>:hex:04000000000000000000000000000000000000000000000000000000000000000000000000000
>000000000000000000000000000000000000000000000000000000000000000000000000000000000
>000000000000000000000000000000000000000000000000000000000000000000000000000000000
>000000000000000000000000000000000000000000000000000000000000000000000000000000000
>000000000000000000000000000000000000000000000000000000000000000000000000000000000
>000000000000000000000000000000000000000000000000000000000000000000000000000000000
>000000000000000000000000000000000000000000000000000000000000000000000000000000000
>000000000000000000000000000000000000000000000000000000000000000000000000000000000
>000000000000000000000000000000000000000000000000000000000000000000000000000000000
>000000000000000000000000000000000000000000000000000000000000000000000000000000000
>000000000000000000000000000000000000000000000000000000000000000000000000000000000
>000000000000000000000000000000000000000000000000000000000000000000000000000000000
>000000000000000000000000000000000000000000000000000000000000000000000000000000000
>000000000000000000000000000000000000000000000000000000000000000000000000000000000
>000000000000000000000000000000000000000000000000000000000000000000000000000000000
>000000000000000000000000000000000000000000000000000000a00000000000000400000000200
>0000cf2f6c0af98d548b94add9724a775fb529f937d0d497cc0a4cf38e58e094605a2e636a7bfe7fc4285d
>fb553f872a607937196cc5959b42e37a11b23b7bc244db3262613631386261303937313632666600393
>9383837373636000000
```

I can generate the FNEK using my PHP lib:
```
$ php -r 'require_once("vendor/autoload.php"); echo \Iqb\Ecryptfs\Util::deriveFNEK("testtest", true), PHP_EOL;'
> cf2f6c0af98d548b94add9724a775fb529f937d0d497cc0a4cf38e58e094605a2e636a7bfe7fc4285dfb553f872a607937196cc5959b42e37a11b23b7bc244db
```

and you can see this key is contained in the kernel key material (because this is a struct with some other information present as well, not only the plain key).

For my cases the keys from the kernel keyring and the PHP-generated match and I can encrypt/decrypt filenames and file contents in both directions.
If the PHP lib fails to derive the correct FNEK from your passphrase you can take the key from the kernel keyring (`keyctl print 808317687 | tail -c -185 | head -c 128`) and try that as a the FNEK in PHP (unhex in PHP first).

**Comment by DennisBirkholz** [comment]
One additional thing: when you extract the wrapped passphrase, the `ecryptfs-unwrap-passphrase` command adds an additional newline to the output. If you then pipe it to e.g. `hexdump`, the resulting hex data will contain the newline.

Try the following command to extract the hex encoded passphrase:
`echo -n "passphrase" | ecryptfs-unwrap-passphrase wrapped-passphrase - | head -c -1 | hexdump -v -e '/1 "%02X"'; echo`

**Comment by PPanon** [comment]
Hmm, well I'm still getting the sigs I had before
ppanon@whiteygu:~$ ecryptfs-insert-wrapped-passphrase-into-keyring
Passphrase: 
Inserted auth tok with sig [ed63554cda292c35] into the user session keyring
ppanon@whiteygu:~$ keyctl list '@u'
2 keys in keyring:
372667940: --alswrv  1000  1000 user: 2ac13a17db223ae3
433512888: --alswrv  1000  1000 user: ed63554cda292c35
ppanon@whiteygu:~$ sudo su
root@whiteygu:/home/ppanon# keyctl print 372667940
keyctl_read_alloc: Permission denied
root@whiteygu:/home/ppanon# keyctl print 433512888
keyctl_read_alloc: Permission denied

and yes, I can't print the kernel FNEK or FKEKEK from the kernel keyring, even as root. Well, maybe that's part of the reason why I can't list anything in the top level of that directory, although it's surprising that I was able to cd into those top level directories somehow and get listings of their contents.

Well, thank you for all your helpful suggestions. I'm not sure there is much left to try at this point.

**Comment by PPanon** [comment]
I tried 
root@whiteygu:/home/ppanon# keyctl setperm 372667940 0x3f3f0000
keyctl_setperm: Permission denied
but that didn't work.

**Comment by DennisBirkholz** [comment]
I am sorry I could not help you, but I am out of ideas. As I am neither a kernel developer nor an expert for the original ecryptfs implementation I don't see there is anything left here to offer, I close the ticket.

**Comment by PPanon** [comment]
Totally understand and thank you for making the effort!
